import type { FoodItem } from "@/lib/types/nutrition";
import type { FoodUnit } from "@/lib/food-parser/units";

/**
 * Seed input for a FoodItem — same shape as FoodItem minus the generated `id`,
 * which the seed loader derives from `slug` (id === slug for seed data).
 */
export type FoodItemSeedInput = FoodItem;

const LAST_UPDATED = "2026-07-01";

/**
 * Master Indian food database seed. Values are per-100g estimates drawn from
 * standard IFCT/USDA-style published references. Simple single-ingredient raw
 * items (plain rice, plain chicken breast, egg, milk, oils, sugar) are marked
 * "verified"; cooked/mixed/composite dishes are marked "estimated" since actual
 * values vary with recipe, oil quantity, and preparation.
 */
export const foodItemSeed: FoodItemSeedInput[] = [
  // ─────────────────────────── EGGS ───────────────────────────
  {
    id: "egg-boiled",
    slug: "egg-boiled",
    name: "Egg, boiled",
    category: "eggs",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "boiled",
    caloriesPer100g: 155,
    proteinPer100g: 13,
    carbsPer100g: 1.1,
    fatPer100g: 11,
    fibrePer100g: 0,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g cooked, edible portion",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "egg-fried",
    slug: "egg-fried",
    name: "Egg, fried",
    category: "eggs",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "pan-fried in oil",
    caloriesPer100g: 196,
    proteinPer100g: 13.6,
    carbsPer100g: 0.8,
    fatPer100g: 15,
    fibrePer100g: 0,
    source: "USDA/IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "egg-bhurji",
    slug: "egg-bhurji",
    name: "Egg bhurji (scrambled, Indian style)",
    category: "eggs",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "scrambled with onion, tomato, spices in oil",
    caloriesPer100g: 175,
    proteinPer100g: 11.5,
    carbsPer100g: 4.5,
    fatPer100g: 13,
    fibrePer100g: 0.8,
    source: "USDA/IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "egg-curry",
    slug: "egg-curry",
    name: "Egg curry (home style)",
    category: "eggs",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "boiled eggs simmered in onion-tomato gravy",
    caloriesPer100g: 148,
    proteinPer100g: 8.2,
    carbsPer100g: 5.5,
    fatPer100g: 10.5,
    fibrePer100g: 1.2,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked (egg + gravy)",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "egg-white-boiled",
    slug: "egg-white-boiled",
    name: "Egg white, boiled",
    category: "eggs",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "boiled",
    caloriesPer100g: 52,
    proteinPer100g: 11,
    carbsPer100g: 0.7,
    fatPer100g: 0.2,
    fibrePer100g: 0,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g cooked",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── CHICKEN ───────────────────────────
  {
    id: "chicken-breast-raw",
    slug: "chicken-breast-raw",
    name: "Chicken breast, raw, skinless",
    category: "chicken",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 120,
    proteinPer100g: 22.5,
    carbsPer100g: 0,
    fatPer100g: 2.6,
    fibrePer100g: 0,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g raw",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "chicken-breast-grilled",
    slug: "chicken-breast-grilled",
    name: "Chicken breast, grilled, skinless",
    category: "chicken",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "grilled, minimal oil",
    caloriesPer100g: 165,
    proteinPer100g: 31,
    carbsPer100g: 0,
    fatPer100g: 3.6,
    fibrePer100g: 0,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g cooked",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "chicken-thigh-raw",
    slug: "chicken-thigh-raw",
    name: "Chicken thigh, raw, skinless",
    category: "chicken",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 143,
    proteinPer100g: 19.9,
    carbsPer100g: 0,
    fatPer100g: 6.9,
    fibrePer100g: 0,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g raw",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "chicken-thigh-cooked",
    slug: "chicken-thigh-cooked",
    name: "Chicken thigh, cooked, skinless",
    category: "chicken",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "roasted",
    caloriesPer100g: 209,
    proteinPer100g: 26,
    carbsPer100g: 0,
    fatPer100g: 10.9,
    fibrePer100g: 0,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g cooked",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "chicken-curry-home-style",
    slug: "chicken-curry-home-style",
    name: "Chicken curry, home style",
    category: "chicken",
    cuisineTag: "south_indian",
    rawCookedState: "cooked",
    preparationMethod: "curry with onion-tomato masala, mustard/sunflower oil",
    caloriesPer100g: 165,
    proteinPer100g: 14,
    carbsPer100g: 5,
    fatPer100g: 10,
    fibrePer100g: 1,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked (meat + gravy)",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "chicken-tikka",
    slug: "chicken-tikka",
    name: "Chicken tikka",
    category: "chicken",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "marinated in yogurt-spice mix, grilled/tandoor",
    caloriesPer100g: 180,
    proteinPer100g: 26,
    carbsPer100g: 3,
    fatPer100g: 7,
    fibrePer100g: 0.4,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "chicken-tandoori",
    slug: "chicken-tandoori",
    name: "Tandoori chicken",
    category: "chicken",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "marinated bone-in chicken, roasted in tandoor",
    caloriesPer100g: 190,
    proteinPer100g: 27,
    carbsPer100g: 2.5,
    fatPer100g: 8,
    fibrePer100g: 0.3,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "chicken-grilled-spiced",
    slug: "chicken-grilled-spiced",
    name: "Chicken, grilled, Indian spiced",
    category: "chicken",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "spice-marinated, grilled",
    caloriesPer100g: 172,
    proteinPer100g: 28,
    carbsPer100g: 1.5,
    fatPer100g: 6,
    fibrePer100g: 0.3,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "chicken-65",
    slug: "chicken-65",
    name: "Chicken 65",
    category: "chicken",
    cuisineTag: "south_indian",
    rawCookedState: "cooked",
    preparationMethod: "deep-fried, spiced batter",
    caloriesPer100g: 260,
    proteinPer100g: 22,
    carbsPer100g: 10,
    fatPer100g: 15,
    fibrePer100g: 0.8,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── MUTTON ───────────────────────────
  {
    id: "mutton-curry",
    slug: "mutton-curry",
    name: "Mutton curry, home style",
    category: "mutton",
    cuisineTag: "south_indian",
    rawCookedState: "cooked",
    preparationMethod: "curry with onion-tomato masala",
    caloriesPer100g: 220,
    proteinPer100g: 17,
    carbsPer100g: 4.5,
    fatPer100g: 15,
    fibrePer100g: 1,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked (meat + gravy)",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "mutton-keema",
    slug: "mutton-keema",
    name: "Mutton keema (minced mutton curry)",
    category: "mutton",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "minced mutton cooked with spices, peas optional",
    caloriesPer100g: 235,
    proteinPer100g: 18,
    carbsPer100g: 5,
    fatPer100g: 16,
    fibrePer100g: 1.2,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "mutton-raw",
    slug: "mutton-raw",
    name: "Mutton, raw, lean",
    category: "mutton",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 143,
    proteinPer100g: 20.6,
    carbsPer100g: 0,
    fatPer100g: 6.3,
    fibrePer100g: 0,
    source: "IFCT reference (verified)",
    measurementBasis: "per 100g raw",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── FISH ───────────────────────────
  {
    id: "fish-curry-rohu",
    slug: "fish-curry-rohu",
    name: "Fish curry (rohu, home style)",
    category: "fish",
    cuisineTag: "south_indian",
    rawCookedState: "cooked",
    preparationMethod: "curry with tamarind-coconut/tomato masala",
    caloriesPer100g: 135,
    proteinPer100g: 15,
    carbsPer100g: 4,
    fatPer100g: 6.5,
    fibrePer100g: 0.8,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked (fish + gravy)",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "fish-fry-pomfret",
    slug: "fish-fry-pomfret",
    name: "Fish fry (pomfret, shallow fried)",
    category: "fish",
    cuisineTag: "south_indian",
    rawCookedState: "cooked",
    preparationMethod: "spice-marinated, shallow fried in oil",
    caloriesPer100g: 210,
    proteinPer100g: 22,
    carbsPer100g: 6,
    fatPer100g: 11,
    fibrePer100g: 0.5,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "fish-grilled",
    slug: "fish-grilled",
    name: "Fish, grilled (generic white fish)",
    category: "fish",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "grilled with light spice marinade",
    caloriesPer100g: 145,
    proteinPer100g: 24,
    carbsPer100g: 0.5,
    fatPer100g: 5,
    fibrePer100g: 0,
    source: "USDA/IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "fish-raw-rohu",
    slug: "fish-raw-rohu",
    name: "Rohu fish, raw",
    category: "fish",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 97,
    proteinPer100g: 16.6,
    carbsPer100g: 0,
    fatPer100g: 2.9,
    fibrePer100g: 0,
    source: "IFCT reference (verified)",
    measurementBasis: "per 100g raw",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── PRAWNS ───────────────────────────
  {
    id: "prawns-curry",
    slug: "prawns-curry",
    name: "Prawn curry, home style",
    category: "prawns",
    cuisineTag: "south_indian",
    rawCookedState: "cooked",
    preparationMethod: "curry with coconut-tomato masala",
    caloriesPer100g: 145,
    proteinPer100g: 17,
    carbsPer100g: 4.5,
    fatPer100g: 6.5,
    fibrePer100g: 0.6,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "prawns-fried",
    slug: "prawns-fried",
    name: "Prawns, fried/roasted with spices",
    category: "prawns",
    cuisineTag: "south_indian",
    rawCookedState: "cooked",
    preparationMethod: "shallow fried with spices",
    caloriesPer100g: 190,
    proteinPer100g: 20,
    carbsPer100g: 6,
    fatPer100g: 9.5,
    fibrePer100g: 0.5,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "prawns-raw",
    slug: "prawns-raw",
    name: "Prawns, raw, peeled",
    category: "prawns",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 85,
    proteinPer100g: 20.3,
    carbsPer100g: 0.2,
    fatPer100g: 0.5,
    fibrePer100g: 0,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g raw",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── WHEY PROTEIN ───────────────────────────
  {
    id: "whey-protein-generic",
    slug: "whey-protein-generic",
    name: "Whey protein powder, generic (per scoop basis)",
    category: "supplements",
    cuisineTag: "generic",
    rawCookedState: "not_applicable",
    preparationMethod: "mixed with water/milk",
    caloriesPer100g: 380,
    proteinPer100g: 75,
    carbsPer100g: 8,
    fatPer100g: 6,
    fibrePer100g: 1,
    source: "Standard nutrition reference (typical whey blend label)",
    measurementBasis: "per 100g powder",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── MILK ───────────────────────────
  {
    id: "milk-full-fat",
    slug: "milk-full-fat",
    name: "Milk, full-fat (buffalo/cow blend, standard)",
    category: "dairy",
    cuisineTag: "generic",
    rawCookedState: "not_applicable",
    preparationMethod: undefined,
    caloriesPer100g: 67,
    proteinPer100g: 3.2,
    carbsPer100g: 4.8,
    fatPer100g: 4.1,
    fibrePer100g: 0,
    source: "IFCT reference (verified)",
    measurementBasis: "per 100ml",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "milk-toned",
    slug: "milk-toned",
    name: "Milk, toned (3% fat)",
    category: "dairy",
    cuisineTag: "generic",
    rawCookedState: "not_applicable",
    preparationMethod: undefined,
    caloriesPer100g: 58,
    proteinPer100g: 3.1,
    carbsPer100g: 4.9,
    fatPer100g: 3,
    fibrePer100g: 0,
    source: "IFCT reference (verified)",
    measurementBasis: "per 100ml",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "milk-skimmed",
    slug: "milk-skimmed",
    name: "Milk, skimmed",
    category: "dairy",
    cuisineTag: "generic",
    rawCookedState: "not_applicable",
    preparationMethod: undefined,
    caloriesPer100g: 35,
    proteinPer100g: 3.4,
    carbsPer100g: 5,
    fatPer100g: 0.2,
    fibrePer100g: 0,
    source: "USDA reference (verified)",
    measurementBasis: "per 100ml",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── CURD / YOGURT ───────────────────────────
  {
    id: "curd-plain",
    slug: "curd-plain",
    name: "Curd / dahi, plain, full-fat",
    category: "dairy",
    cuisineTag: "generic",
    rawCookedState: "not_applicable",
    preparationMethod: undefined,
    caloriesPer100g: 60,
    proteinPer100g: 3.5,
    carbsPer100g: 4.7,
    fatPer100g: 3.3,
    fibrePer100g: 0,
    source: "IFCT reference (verified)",
    measurementBasis: "per 100g",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "yogurt-greek",
    slug: "yogurt-greek",
    name: "Greek yogurt, plain",
    category: "dairy",
    cuisineTag: "generic",
    rawCookedState: "not_applicable",
    preparationMethod: "strained",
    caloriesPer100g: 97,
    proteinPer100g: 9,
    carbsPer100g: 3.9,
    fatPer100g: 5,
    fibrePer100g: 0,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "curd-low-fat",
    slug: "curd-low-fat",
    name: "Curd / dahi, low-fat",
    category: "dairy",
    cuisineTag: "generic",
    rawCookedState: "not_applicable",
    preparationMethod: undefined,
    caloriesPer100g: 40,
    proteinPer100g: 3.8,
    carbsPer100g: 4.5,
    fatPer100g: 1,
    fibrePer100g: 0,
    source: "IFCT reference (verified)",
    measurementBasis: "per 100g",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── PANEER ───────────────────────────
  {
    id: "paneer-raw",
    slug: "paneer-raw",
    name: "Paneer, raw",
    category: "dairy",
    cuisineTag: "north_indian",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 265,
    proteinPer100g: 18.3,
    carbsPer100g: 1.2,
    fatPer100g: 20.8,
    fibrePer100g: 0,
    source: "IFCT reference (verified)",
    measurementBasis: "per 100g raw",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "paneer-bhurji",
    slug: "paneer-bhurji",
    name: "Paneer bhurji (scrambled)",
    category: "dairy",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "crumbled paneer sauteed with onion, tomato, spices",
    caloriesPer100g: 240,
    proteinPer100g: 14,
    carbsPer100g: 5,
    fatPer100g: 18,
    fibrePer100g: 1,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "paneer-curry",
    slug: "paneer-curry",
    name: "Paneer curry (paneer masala, home style)",
    category: "dairy",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "paneer cubes in onion-tomato-cream gravy",
    caloriesPer100g: 220,
    proteinPer100g: 11,
    carbsPer100g: 7,
    fatPer100g: 16,
    fibrePer100g: 1.3,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked (paneer + gravy)",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── RICE ───────────────────────────
  {
    id: "rice-white-cooked",
    slug: "rice-white-cooked",
    name: "Rice, white, cooked",
    category: "grains",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "boiled/steamed",
    caloriesPer100g: 130,
    proteinPer100g: 2.7,
    carbsPer100g: 28,
    fatPer100g: 0.3,
    fibrePer100g: 0.4,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g cooked",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "rice-brown-cooked",
    slug: "rice-brown-cooked",
    name: "Rice, brown, cooked",
    category: "grains",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "boiled/steamed",
    caloriesPer100g: 123,
    proteinPer100g: 2.7,
    carbsPer100g: 25.6,
    fatPer100g: 1,
    fibrePer100g: 1.8,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g cooked",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "biryani-chicken",
    slug: "biryani-chicken",
    name: "Chicken biryani",
    category: "grains",
    cuisineTag: "south_indian",
    rawCookedState: "cooked",
    preparationMethod: "layered rice and chicken, cooked with spices and oil/ghee",
    caloriesPer100g: 165,
    proteinPer100g: 8,
    carbsPer100g: 19,
    fatPer100g: 6,
    fibrePer100g: 0.8,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "pulao-vegetable",
    slug: "pulao-vegetable",
    name: "Vegetable pulao",
    category: "grains",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "rice cooked with mixed vegetables, mild spices, oil/ghee",
    caloriesPer100g: 150,
    proteinPer100g: 3.2,
    carbsPer100g: 24,
    fatPer100g: 4.5,
    fibrePer100g: 1.2,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "rice-raw-uncooked",
    slug: "rice-raw-uncooked",
    name: "Rice, white, raw/uncooked",
    category: "grains",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 345,
    proteinPer100g: 6.8,
    carbsPer100g: 78,
    fatPer100g: 0.5,
    fibrePer100g: 0.2,
    source: "IFCT reference (verified)",
    measurementBasis: "per 100g raw",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── ROTI / BREADS ───────────────────────────
  {
    id: "roti-whole-wheat",
    slug: "roti-whole-wheat",
    name: "Roti, whole wheat (no oil/ghee)",
    category: "breads",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "tawa-roasted, dry",
    caloriesPer100g: 280,
    proteinPer100g: 8.5,
    carbsPer100g: 55,
    fatPer100g: 3.5,
    fibrePer100g: 9.6,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "chapati-plain",
    slug: "chapati-plain",
    name: "Chapati, plain (thin, whole wheat)",
    category: "breads",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "tawa-roasted, dry",
    caloriesPer100g: 275,
    proteinPer100g: 8.7,
    carbsPer100g: 54,
    fatPer100g: 3.2,
    fibrePer100g: 9.2,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "paratha-plain",
    slug: "paratha-plain",
    name: "Paratha, plain (with ghee/oil)",
    category: "breads",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "layered, pan-fried with ghee",
    caloriesPer100g: 330,
    proteinPer100g: 7.5,
    carbsPer100g: 45,
    fatPer100g: 13,
    fibrePer100g: 6.5,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "paratha-aloo",
    slug: "paratha-aloo",
    name: "Aloo paratha (potato stuffed)",
    category: "breads",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "stuffed with spiced potato, pan-fried with oil/ghee",
    caloriesPer100g: 260,
    proteinPer100g: 6,
    carbsPer100g: 35,
    fatPer100g: 10.5,
    fibrePer100g: 3.5,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "naan-plain",
    slug: "naan-plain",
    name: "Naan, plain (tandoor)",
    category: "breads",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "leavened, baked in tandoor, brushed with butter",
    caloriesPer100g: 310,
    proteinPer100g: 8.5,
    carbsPer100g: 50,
    fatPer100g: 8.5,
    fibrePer100g: 2.2,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── SOUTH INDIAN BREAKFAST ───────────────────────────
  {
    id: "dosa-plain",
    slug: "dosa-plain",
    name: "Dosa, plain",
    category: "breakfast",
    cuisineTag: "south_indian",
    rawCookedState: "cooked",
    preparationMethod: "fermented rice-urad batter, roasted on tawa with oil",
    caloriesPer100g: 168,
    proteinPer100g: 3.9,
    carbsPer100g: 28,
    fatPer100g: 4.5,
    fibrePer100g: 1,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "idli",
    slug: "idli",
    name: "Idli",
    category: "breakfast",
    cuisineTag: "south_indian",
    rawCookedState: "cooked",
    preparationMethod: "steamed fermented rice-urad batter",
    caloriesPer100g: 130,
    proteinPer100g: 4.5,
    carbsPer100g: 26,
    fatPer100g: 0.5,
    fibrePer100g: 1.2,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "upma",
    slug: "upma",
    name: "Upma (semolina)",
    category: "breakfast",
    cuisineTag: "south_indian",
    rawCookedState: "cooked",
    preparationMethod: "roasted semolina cooked with vegetables and oil",
    caloriesPer100g: 150,
    proteinPer100g: 3.5,
    carbsPer100g: 22,
    fatPer100g: 5.5,
    fibrePer100g: 1.5,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "poha",
    slug: "poha",
    name: "Poha (flattened rice)",
    category: "breakfast",
    cuisineTag: "west_indian",
    rawCookedState: "cooked",
    preparationMethod: "flattened rice tempered with onion, peanuts, oil",
    caloriesPer100g: 158,
    proteinPer100g: 3.4,
    carbsPer100g: 24,
    fatPer100g: 5.2,
    fibrePer100g: 1.4,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "oats-cooked-plain",
    slug: "oats-cooked-plain",
    name: "Oats, cooked, plain (with water)",
    category: "breakfast",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "boiled in water",
    caloriesPer100g: 71,
    proteinPer100g: 2.5,
    carbsPer100g: 12,
    fatPer100g: 1.5,
    fibrePer100g: 1.7,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g cooked",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "oats-raw-rolled",
    slug: "oats-raw-rolled",
    name: "Oats, rolled, raw/dry",
    category: "breakfast",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 389,
    proteinPer100g: 16.9,
    carbsPer100g: 66,
    fatPer100g: 6.9,
    fibrePer100g: 10.6,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g raw/dry",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── DALS ───────────────────────────
  {
    id: "toor-dal-cooked",
    slug: "toor-dal-cooked",
    name: "Toor dal (arhar), cooked",
    category: "dal",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "boiled, tempered with oil/ghee and spices",
    caloriesPer100g: 118,
    proteinPer100g: 7.5,
    carbsPer100g: 17,
    fatPer100g: 2.5,
    fibrePer100g: 4.5,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "moong-dal-cooked",
    slug: "moong-dal-cooked",
    name: "Moong dal (yellow), cooked",
    category: "dal",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "boiled, tempered with light oil",
    caloriesPer100g: 105,
    proteinPer100g: 7.8,
    carbsPer100g: 15,
    fatPer100g: 2,
    fibrePer100g: 4,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "chana-dal-cooked",
    slug: "chana-dal-cooked",
    name: "Chana dal, cooked",
    category: "dal",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "boiled, tempered with oil and spices",
    caloriesPer100g: 134,
    proteinPer100g: 8.4,
    carbsPer100g: 20,
    fatPer100g: 2.8,
    fibrePer100g: 5.5,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "masoor-dal-cooked",
    slug: "masoor-dal-cooked",
    name: "Masoor dal (red lentil), cooked",
    category: "dal",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "boiled, tempered with light oil",
    caloriesPer100g: 108,
    proteinPer100g: 7.6,
    carbsPer100g: 16,
    fatPer100g: 2,
    fibrePer100g: 4.2,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "urad-dal-cooked",
    slug: "urad-dal-cooked",
    name: "Urad dal (black gram), cooked",
    category: "dal",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "boiled, tempered with ghee/oil",
    caloriesPer100g: 128,
    proteinPer100g: 8.9,
    carbsPer100g: 18,
    fatPer100g: 2.8,
    fibrePer100g: 5,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── RAJMA / CHOLE ───────────────────────────
  {
    id: "rajma-curry",
    slug: "rajma-curry",
    name: "Rajma (kidney bean curry)",
    category: "legumes",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "boiled kidney beans in onion-tomato gravy",
    caloriesPer100g: 130,
    proteinPer100g: 7.5,
    carbsPer100g: 18,
    fatPer100g: 3.5,
    fibrePer100g: 5.5,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "chole-curry",
    slug: "chole-curry",
    name: "Chole (chickpea curry)",
    category: "legumes",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "boiled chickpeas in spiced onion-tomato gravy",
    caloriesPer100g: 140,
    proteinPer100g: 7.2,
    carbsPer100g: 19,
    fatPer100g: 4.5,
    fibrePer100g: 6,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── SAMBAR / RASAM ───────────────────────────
  {
    id: "sambar",
    slug: "sambar",
    name: "Sambar",
    category: "south_indian_curries",
    cuisineTag: "south_indian",
    rawCookedState: "cooked",
    preparationMethod: "toor dal and vegetables cooked with tamarind and sambar powder",
    caloriesPer100g: 75,
    proteinPer100g: 3.5,
    carbsPer100g: 10,
    fatPer100g: 2,
    fibrePer100g: 2.5,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "rasam",
    slug: "rasam",
    name: "Rasam",
    category: "south_indian_curries",
    cuisineTag: "south_indian",
    rawCookedState: "cooked",
    preparationMethod: "thin tamarind-tomato broth with rasam powder",
    caloriesPer100g: 35,
    proteinPer100g: 1.5,
    carbsPer100g: 5.5,
    fatPer100g: 1,
    fibrePer100g: 1,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── VEGETABLE CURRIES ───────────────────────────
  {
    id: "aloo-sabzi",
    slug: "aloo-sabzi",
    name: "Aloo sabzi (dry potato curry)",
    category: "vegetables",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "potato cubes tempered with oil and spices",
    caloriesPer100g: 130,
    proteinPer100g: 2.3,
    carbsPer100g: 18,
    fatPer100g: 5.5,
    fibrePer100g: 2,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "bhindi-fry",
    slug: "bhindi-fry",
    name: "Bhindi fry (okra, dry sabzi)",
    category: "vegetables",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "sliced okra sauteed in oil with spices",
    caloriesPer100g: 105,
    proteinPer100g: 2.5,
    carbsPer100g: 9,
    fatPer100g: 6.5,
    fibrePer100g: 3.5,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "baingan-bharta",
    slug: "baingan-bharta",
    name: "Baingan bharta (roasted eggplant mash)",
    category: "vegetables",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "fire-roasted brinjal mashed and cooked with onion-tomato",
    caloriesPer100g: 95,
    proteinPer100g: 2,
    carbsPer100g: 9,
    fatPer100g: 5.5,
    fibrePer100g: 3.2,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "mixed-vegetable-curry",
    slug: "mixed-vegetable-curry",
    name: "Mixed vegetable curry",
    category: "vegetables",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "assorted vegetables in light onion-tomato gravy",
    caloriesPer100g: 100,
    proteinPer100g: 2.8,
    carbsPer100g: 10,
    fatPer100g: 5,
    fibrePer100g: 2.8,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "palak-paneer",
    slug: "palak-paneer",
    name: "Palak paneer",
    category: "vegetables",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "pureed spinach gravy with paneer cubes",
    caloriesPer100g: 165,
    proteinPer100g: 7.5,
    carbsPer100g: 6.5,
    fatPer100g: 12,
    fibrePer100g: 2.5,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "cabbage-sabzi",
    slug: "cabbage-sabzi",
    name: "Cabbage sabzi, dry",
    category: "vegetables",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "shredded cabbage sauteed with light oil and spices",
    caloriesPer100g: 70,
    proteinPer100g: 1.8,
    carbsPer100g: 7,
    fatPer100g: 4,
    fibrePer100g: 2.5,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── FRUITS ───────────────────────────
  {
    id: "banana",
    slug: "banana",
    name: "Banana, ripe",
    category: "fruits",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 89,
    proteinPer100g: 1.1,
    carbsPer100g: 23,
    fatPer100g: 0.3,
    fibrePer100g: 2.6,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g edible portion",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "apple",
    slug: "apple",
    name: "Apple, with skin",
    category: "fruits",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 52,
    proteinPer100g: 0.3,
    carbsPer100g: 14,
    fatPer100g: 0.2,
    fibrePer100g: 2.4,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g edible portion",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "papaya",
    slug: "papaya",
    name: "Papaya, ripe",
    category: "fruits",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 43,
    proteinPer100g: 0.5,
    carbsPer100g: 11,
    fatPer100g: 0.3,
    fibrePer100g: 1.7,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g edible portion",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "orange",
    slug: "orange",
    name: "Orange",
    category: "fruits",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 47,
    proteinPer100g: 0.9,
    carbsPer100g: 12,
    fatPer100g: 0.1,
    fibrePer100g: 2.4,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g edible portion",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "mango",
    slug: "mango",
    name: "Mango, ripe",
    category: "fruits",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 60,
    proteinPer100g: 0.8,
    carbsPer100g: 15,
    fatPer100g: 0.4,
    fibrePer100g: 1.6,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g edible portion",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "watermelon",
    slug: "watermelon",
    name: "Watermelon",
    category: "fruits",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 30,
    proteinPer100g: 0.6,
    carbsPer100g: 7.6,
    fatPer100g: 0.2,
    fibrePer100g: 0.4,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g edible portion",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── NUTS ───────────────────────────
  {
    id: "almonds",
    slug: "almonds",
    name: "Almonds, raw",
    category: "nuts",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 579,
    proteinPer100g: 21.2,
    carbsPer100g: 22,
    fatPer100g: 49.9,
    fibrePer100g: 12.5,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g raw",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "peanuts",
    slug: "peanuts",
    name: "Peanuts, roasted",
    category: "nuts",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "dry roasted",
    caloriesPer100g: 567,
    proteinPer100g: 25.8,
    carbsPer100g: 16.1,
    fatPer100g: 49.2,
    fibrePer100g: 8.5,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g roasted",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "cashews",
    slug: "cashews",
    name: "Cashews, raw",
    category: "nuts",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 553,
    proteinPer100g: 18.2,
    carbsPer100g: 30.2,
    fatPer100g: 43.9,
    fibrePer100g: 3.3,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g raw",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "walnuts",
    slug: "walnuts",
    name: "Walnuts, raw",
    category: "nuts",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 654,
    proteinPer100g: 15.2,
    carbsPer100g: 13.7,
    fatPer100g: 65.2,
    fibrePer100g: 6.7,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g raw",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── OILS / GHEE ───────────────────────────
  {
    id: "sunflower-oil",
    slug: "sunflower-oil",
    name: "Sunflower oil",
    category: "oils",
    cuisineTag: "generic",
    rawCookedState: "not_applicable",
    preparationMethod: undefined,
    caloriesPer100g: 884,
    proteinPer100g: 0,
    carbsPer100g: 0,
    fatPer100g: 100,
    fibrePer100g: 0,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "mustard-oil",
    slug: "mustard-oil",
    name: "Mustard oil",
    category: "oils",
    cuisineTag: "generic",
    rawCookedState: "not_applicable",
    preparationMethod: undefined,
    caloriesPer100g: 884,
    proteinPer100g: 0,
    carbsPer100g: 0,
    fatPer100g: 100,
    fibrePer100g: 0,
    source: "USDA/IFCT reference (verified)",
    measurementBasis: "per 100g",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "olive-oil",
    slug: "olive-oil",
    name: "Olive oil",
    category: "oils",
    cuisineTag: "generic",
    rawCookedState: "not_applicable",
    preparationMethod: undefined,
    caloriesPer100g: 884,
    proteinPer100g: 0,
    carbsPer100g: 0,
    fatPer100g: 100,
    fibrePer100g: 0,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "ghee",
    slug: "ghee",
    name: "Ghee (clarified butter)",
    category: "oils",
    cuisineTag: "generic",
    rawCookedState: "not_applicable",
    preparationMethod: undefined,
    caloriesPer100g: 900,
    proteinPer100g: 0,
    carbsPer100g: 0,
    fatPer100g: 100,
    fibrePer100g: 0,
    source: "IFCT reference (verified)",
    measurementBasis: "per 100g",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── BEVERAGES ───────────────────────────
  {
    id: "tea-with-milk-sugar",
    slug: "tea-with-milk-sugar",
    name: "Tea, with milk and sugar (chai)",
    category: "beverages",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "brewed with milk and sugar",
    caloriesPer100g: 45,
    proteinPer100g: 1,
    carbsPer100g: 6,
    fatPer100g: 1.6,
    fibrePer100g: 0,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100ml prepared",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "coffee-with-milk-sugar",
    slug: "coffee-with-milk-sugar",
    name: "Coffee, with milk and sugar (filter coffee)",
    category: "beverages",
    cuisineTag: "south_indian",
    rawCookedState: "cooked",
    preparationMethod: "decoction brewed with milk and sugar",
    caloriesPer100g: 48,
    proteinPer100g: 1.1,
    carbsPer100g: 6.5,
    fatPer100g: 1.7,
    fibrePer100g: 0,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100ml prepared",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "black-tea-unsweetened",
    slug: "black-tea-unsweetened",
    name: "Black tea, unsweetened",
    category: "beverages",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "brewed, no milk/sugar",
    caloriesPer100g: 1,
    proteinPer100g: 0,
    carbsPer100g: 0.3,
    fatPer100g: 0,
    fibrePer100g: 0,
    source: "USDA reference (verified)",
    measurementBasis: "per 100ml prepared",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── SUGAR ───────────────────────────
  {
    id: "sugar-white",
    slug: "sugar-white",
    name: "Sugar, white, refined",
    category: "sweeteners",
    cuisineTag: "generic",
    rawCookedState: "not_applicable",
    preparationMethod: undefined,
    caloriesPer100g: 387,
    proteinPer100g: 0,
    carbsPer100g: 100,
    fatPer100g: 0,
    fibrePer100g: 0,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "jaggery",
    slug: "jaggery",
    name: "Jaggery (gur)",
    category: "sweeteners",
    cuisineTag: "generic",
    rawCookedState: "not_applicable",
    preparationMethod: undefined,
    caloriesPer100g: 383,
    proteinPer100g: 0.4,
    carbsPer100g: 98,
    fatPer100g: 0.1,
    fibrePer100g: 0,
    source: "IFCT reference (verified)",
    measurementBasis: "per 100g",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── SNACKS ───────────────────────────
  {
    id: "namkeen-mixture",
    slug: "namkeen-mixture",
    name: "Namkeen mixture (fried savory snack mix)",
    category: "snacks",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "deep-fried gram flour/lentil mixture",
    caloriesPer100g: 500,
    proteinPer100g: 14,
    carbsPer100g: 45,
    fatPer100g: 30,
    fibrePer100g: 6,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "biscuits-marie",
    slug: "biscuits-marie",
    name: "Biscuits, Marie (plain sweet)",
    category: "snacks",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "baked",
    caloriesPer100g: 435,
    proteinPer100g: 7.5,
    carbsPer100g: 75,
    fatPer100g: 12,
    fibrePer100g: 2,
    source: "Standard nutrition reference (estimated)",
    measurementBasis: "per 100g",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "biscuits-digestive",
    slug: "biscuits-digestive",
    name: "Biscuits, digestive (whole wheat)",
    category: "snacks",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "baked",
    caloriesPer100g: 470,
    proteinPer100g: 7,
    carbsPer100g: 65,
    fatPer100g: 20,
    fibrePer100g: 4,
    source: "Standard nutrition reference (estimated)",
    measurementBasis: "per 100g",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "samosa",
    slug: "samosa",
    name: "Samosa (potato filled, fried)",
    category: "snacks",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "deep-fried pastry with spiced potato filling",
    caloriesPer100g: 308,
    proteinPer100g: 5,
    carbsPer100g: 32,
    fatPer100g: 18,
    fibrePer100g: 2.5,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── RESTAURANT-STYLE ───────────────────────────
  {
    id: "butter-chicken",
    slug: "butter-chicken",
    name: "Butter chicken (murgh makhani)",
    category: "restaurant",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "tandoori chicken in tomato-butter-cream gravy",
    caloriesPer100g: 220,
    proteinPer100g: 14,
    carbsPer100g: 7,
    fatPer100g: 15.5,
    fibrePer100g: 1,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked (chicken + gravy)",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "chicken-tikka-masala",
    slug: "chicken-tikka-masala",
    name: "Chicken tikka masala",
    category: "restaurant",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "grilled chicken tikka in spiced tomato-cream gravy",
    caloriesPer100g: 195,
    proteinPer100g: 15.5,
    carbsPer100g: 6,
    fatPer100g: 12.5,
    fibrePer100g: 1,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "dal-makhani",
    slug: "dal-makhani",
    name: "Dal makhani",
    category: "restaurant",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "black lentils and rajma slow-cooked with butter and cream",
    caloriesPer100g: 165,
    proteinPer100g: 6.5,
    carbsPer100g: 15,
    fatPer100g: 9.5,
    fibrePer100g: 4,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "paneer-tikka-masala",
    slug: "paneer-tikka-masala",
    name: "Paneer tikka masala",
    category: "restaurant",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "grilled paneer cubes in spiced tomato-cream gravy",
    caloriesPer100g: 230,
    proteinPer100g: 10.5,
    carbsPer100g: 8,
    fatPer100g: 17,
    fibrePer100g: 1.4,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },

  // ─────────────────────────── ADDITIONAL STAPLES / VARIETY ───────────────────────────
  {
    id: "curd-rice",
    slug: "curd-rice",
    name: "Curd rice",
    category: "grains",
    cuisineTag: "south_indian",
    rawCookedState: "cooked",
    preparationMethod: "cooked rice mixed with curd, tempered",
    caloriesPer100g: 115,
    proteinPer100g: 3.2,
    carbsPer100g: 17,
    fatPer100g: 3,
    fibrePer100g: 0.5,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "lemon-rice",
    slug: "lemon-rice",
    name: "Lemon rice",
    category: "grains",
    cuisineTag: "south_indian",
    rawCookedState: "cooked",
    preparationMethod: "cooked rice tempered with lemon juice, peanuts, curry leaves",
    caloriesPer100g: 155,
    proteinPer100g: 3,
    carbsPer100g: 24,
    fatPer100g: 5,
    fibrePer100g: 0.8,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "besan-chilla",
    slug: "besan-chilla",
    name: "Besan chilla (gram flour savory pancake)",
    category: "breakfast",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "gram flour batter with vegetables, pan-fried with oil",
    caloriesPer100g: 170,
    proteinPer100g: 8,
    carbsPer100g: 18,
    fatPer100g: 7.5,
    fibrePer100g: 3,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "sweet-potato-boiled",
    slug: "sweet-potato-boiled",
    name: "Sweet potato, boiled",
    category: "vegetables",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "boiled with skin",
    caloriesPer100g: 86,
    proteinPer100g: 1.6,
    carbsPer100g: 20,
    fatPer100g: 0.1,
    fibrePer100g: 3,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g cooked",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "potato-boiled",
    slug: "potato-boiled",
    name: "Potato, boiled with skin",
    category: "vegetables",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "boiled",
    caloriesPer100g: 87,
    proteinPer100g: 1.9,
    carbsPer100g: 20,
    fatPer100g: 0.1,
    fibrePer100g: 1.8,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g cooked",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "cucumber",
    slug: "cucumber",
    name: "Cucumber, raw",
    category: "vegetables",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 15,
    proteinPer100g: 0.7,
    carbsPer100g: 3.6,
    fatPer100g: 0.1,
    fibrePer100g: 0.5,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g raw",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "tomato",
    slug: "tomato",
    name: "Tomato, raw",
    category: "vegetables",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 18,
    proteinPer100g: 0.9,
    carbsPer100g: 3.9,
    fatPer100g: 0.2,
    fibrePer100g: 1.2,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g raw",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "onion-raw",
    slug: "onion-raw",
    name: "Onion, raw",
    category: "vegetables",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 40,
    proteinPer100g: 1.1,
    carbsPer100g: 9.3,
    fatPer100g: 0.1,
    fibrePer100g: 1.7,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g raw",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "spinach-raw",
    slug: "spinach-raw",
    name: "Spinach, raw",
    category: "vegetables",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 23,
    proteinPer100g: 2.9,
    carbsPer100g: 3.6,
    fatPer100g: 0.4,
    fibrePer100g: 2.2,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g raw",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "carrot-raw",
    slug: "carrot-raw",
    name: "Carrot, raw",
    category: "vegetables",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 41,
    proteinPer100g: 0.9,
    carbsPer100g: 9.6,
    fatPer100g: 0.2,
    fibrePer100g: 2.8,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g raw",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "cauliflower-sabzi",
    slug: "cauliflower-sabzi",
    name: "Cauliflower sabzi (gobi, dry)",
    category: "vegetables",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "florets sauteed with oil and spices",
    caloriesPer100g: 95,
    proteinPer100g: 2.3,
    carbsPer100g: 8,
    fatPer100g: 5.8,
    fibrePer100g: 2.5,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "sprouts-salad",
    slug: "sprouts-salad",
    name: "Sprouts salad (moong sprouts, raw veg)",
    category: "salads",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: "sprouted moong with chopped onion, tomato, lemon",
    caloriesPer100g: 80,
    proteinPer100g: 6,
    carbsPer100g: 12,
    fatPer100g: 1.2,
    fibrePer100g: 3.5,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "boiled-chickpea-salad",
    slug: "boiled-chickpea-salad",
    name: "Boiled chickpea salad (kala chana chaat)",
    category: "salads",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "boiled chickpeas with onion, tomato, lemon, chaat masala",
    caloriesPer100g: 150,
    proteinPer100g: 8.5,
    carbsPer100g: 22,
    fatPer100g: 3,
    fibrePer100g: 6.5,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "brown-bread",
    slug: "brown-bread",
    name: "Bread, brown/whole wheat",
    category: "breads",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "baked, sliced",
    caloriesPer100g: 247,
    proteinPer100g: 9,
    carbsPer100g: 41,
    fatPer100g: 4.2,
    fibrePer100g: 6.5,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "white-bread",
    slug: "white-bread",
    name: "Bread, white",
    category: "breads",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "baked, sliced",
    caloriesPer100g: 265,
    proteinPer100g: 9,
    carbsPer100g: 49,
    fatPer100g: 3.2,
    fibrePer100g: 2.7,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "omelette-plain",
    slug: "omelette-plain",
    name: "Omelette, plain (2 egg, minimal oil)",
    category: "eggs",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "beaten eggs, pan-fried with minimal oil",
    caloriesPer100g: 190,
    proteinPer100g: 13.5,
    carbsPer100g: 1.5,
    fatPer100g: 14.5,
    fibrePer100g: 0,
    source: "USDA/IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "chicken-soup",
    slug: "chicken-soup",
    name: "Chicken soup, clear",
    category: "soups",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "boiled chicken stock with shredded chicken and vegetables",
    caloriesPer100g: 45,
    proteinPer100g: 5.5,
    carbsPer100g: 2.5,
    fatPer100g: 1.5,
    fibrePer100g: 0.3,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "buttermilk-spiced",
    slug: "buttermilk-spiced",
    name: "Buttermilk, spiced (chaas)",
    category: "beverages",
    cuisineTag: "generic",
    rawCookedState: "not_applicable",
    preparationMethod: "diluted curd with spices",
    caloriesPer100g: 28,
    proteinPer100g: 1.6,
    carbsPer100g: 2.8,
    fatPer100g: 1.2,
    fibrePer100g: 0,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100ml",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "coconut-chutney",
    slug: "coconut-chutney",
    name: "Coconut chutney",
    category: "condiments",
    cuisineTag: "south_indian",
    rawCookedState: "cooked",
    preparationMethod: "ground coconut with green chilli, tempered",
    caloriesPer100g: 230,
    proteinPer100g: 3.5,
    carbsPer100g: 8,
    fatPer100g: 21,
    fibrePer100g: 3,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "peanut-chutney",
    slug: "peanut-chutney",
    name: "Peanut chutney",
    category: "condiments",
    cuisineTag: "south_indian",
    rawCookedState: "cooked",
    preparationMethod: "ground roasted peanuts with chilli, tempered",
    caloriesPer100g: 280,
    proteinPer100g: 11,
    carbsPer100g: 10,
    fatPer100g: 22,
    fibrePer100g: 4,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "chicken-stew-kerala",
    slug: "chicken-stew-kerala",
    name: "Kerala-style chicken stew",
    category: "chicken",
    cuisineTag: "south_indian",
    rawCookedState: "cooked",
    preparationMethod: "coconut milk based mild stew with potato and spices",
    caloriesPer100g: 150,
    proteinPer100g: 12,
    carbsPer100g: 6,
    fatPer100g: 9,
    fibrePer100g: 1,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "egg-roll-kathi",
    slug: "egg-roll-kathi",
    name: "Egg kathi roll",
    category: "restaurant",
    cuisineTag: "east_indian",
    rawCookedState: "cooked",
    preparationMethod: "paratha wrapped with fried egg and onion filling",
    caloriesPer100g: 250,
    proteinPer100g: 9.5,
    carbsPer100g: 28,
    fatPer100g: 11,
    fibrePer100g: 2,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "raita",
    slug: "raita",
    name: "Raita (cucumber curd salad)",
    category: "dairy",
    cuisineTag: "generic",
    rawCookedState: "not_applicable",
    preparationMethod: "curd mixed with chopped cucumber and light spices",
    caloriesPer100g: 55,
    proteinPer100g: 2.8,
    carbsPer100g: 4.5,
    fatPer100g: 2.8,
    fibrePer100g: 0.4,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "chicken-drumstick-roasted",
    slug: "chicken-drumstick-roasted",
    name: "Chicken drumstick, roasted, skinless",
    category: "chicken",
    cuisineTag: "generic",
    rawCookedState: "cooked",
    preparationMethod: "oven roasted",
    caloriesPer100g: 172,
    proteinPer100g: 28.3,
    carbsPer100g: 0,
    fatPer100g: 5.7,
    fibrePer100g: 0,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g cooked",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "fish-curry-pomfret",
    slug: "fish-curry-pomfret",
    name: "Fish curry (pomfret, coconut based)",
    category: "fish",
    cuisineTag: "south_indian",
    rawCookedState: "cooked",
    preparationMethod: "curry with coconut-tamarind masala",
    caloriesPer100g: 150,
    proteinPer100g: 16,
    carbsPer100g: 4.5,
    fatPer100g: 7.5,
    fibrePer100g: 0.7,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "grapes",
    slug: "grapes",
    name: "Grapes, green",
    category: "fruits",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 69,
    proteinPer100g: 0.7,
    carbsPer100g: 18,
    fatPer100g: 0.2,
    fibrePer100g: 0.9,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g edible portion",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "pomegranate",
    slug: "pomegranate",
    name: "Pomegranate",
    category: "fruits",
    cuisineTag: "generic",
    rawCookedState: "raw",
    preparationMethod: undefined,
    caloriesPer100g: 83,
    proteinPer100g: 1.7,
    carbsPer100g: 19,
    fatPer100g: 1.2,
    fibrePer100g: 4,
    source: "USDA reference (verified)",
    measurementBasis: "per 100g edible portion (arils)",
    reliability: "verified",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "methi-sabzi",
    slug: "methi-sabzi",
    name: "Methi sabzi (fenugreek leaves, dry)",
    category: "vegetables",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "chopped fenugreek leaves sauteed with oil and spices",
    caloriesPer100g: 90,
    proteinPer100g: 3.5,
    carbsPer100g: 6,
    fatPer100g: 5.5,
    fibrePer100g: 3,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
  {
    id: "fish-tandoori",
    slug: "fish-tandoori",
    name: "Tandoori fish",
    category: "fish",
    cuisineTag: "north_indian",
    rawCookedState: "cooked",
    preparationMethod: "yogurt-spice marinated, roasted in tandoor",
    caloriesPer100g: 165,
    proteinPer100g: 23,
    carbsPer100g: 3,
    fatPer100g: 6.5,
    fibrePer100g: 0.4,
    source: "IFCT reference (estimated)",
    measurementBasis: "per 100g cooked",
    reliability: "estimated",
    lastUpdated: LAST_UPDATED,
    isCustom: false,
    ownerUserId: null,
  },
];

// ─────────────────────────── FOOD SERVINGS ───────────────────────────

export const foodServingSeed: {
  foodSlug: string;
  unit: FoodUnit;
  gramsEquivalent: number;
  label: string;
  isDefault?: boolean;
}[] = [
  // Eggs
  { foodSlug: "egg-boiled", unit: "piece", gramsEquivalent: 50, label: "1 egg", isDefault: true },
  { foodSlug: "egg-fried", unit: "piece", gramsEquivalent: 55, label: "1 fried egg", isDefault: true },
  { foodSlug: "egg-white-boiled", unit: "piece", gramsEquivalent: 33, label: "1 egg white", isDefault: true },
  { foodSlug: "egg-bhurji", unit: "katori", gramsEquivalent: 120, label: "1 katori", isDefault: true },
  { foodSlug: "egg-curry", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },
  { foodSlug: "omelette-plain", unit: "piece", gramsEquivalent: 120, label: "1 omelette (2 eggs)", isDefault: true },

  // Chicken
  { foodSlug: "chicken-curry-home-style", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },
  { foodSlug: "chicken-tikka", unit: "piece", gramsEquivalent: 40, label: "1 piece", isDefault: true },
  { foodSlug: "chicken-tandoori", unit: "piece", gramsEquivalent: 150, label: "1 leg piece", isDefault: true },
  { foodSlug: "chicken-65", unit: "serving", gramsEquivalent: 150, label: "1 plate", isDefault: true },
  { foodSlug: "chicken-stew-kerala", unit: "bowl", gramsEquivalent: 200, label: "1 bowl", isDefault: true },
  { foodSlug: "chicken-drumstick-roasted", unit: "piece", gramsEquivalent: 90, label: "1 drumstick", isDefault: true },

  // Mutton
  { foodSlug: "mutton-curry", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },
  { foodSlug: "mutton-keema", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },

  // Fish / prawns
  { foodSlug: "fish-curry-rohu", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },
  { foodSlug: "fish-fry-pomfret", unit: "piece", gramsEquivalent: 100, label: "1 piece", isDefault: true },
  { foodSlug: "prawns-curry", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },
  { foodSlug: "fish-curry-pomfret", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },
  { foodSlug: "fish-tandoori", unit: "piece", gramsEquivalent: 100, label: "1 piece", isDefault: true },

  // Whey protein
  { foodSlug: "whey-protein-generic", unit: "scoop", gramsEquivalent: 30, label: "1 scoop", isDefault: true },

  // Milk / beverages
  { foodSlug: "milk-full-fat", unit: "glass", gramsEquivalent: 250, label: "1 glass", isDefault: true },
  { foodSlug: "milk-toned", unit: "glass", gramsEquivalent: 250, label: "1 glass", isDefault: true },
  { foodSlug: "milk-skimmed", unit: "glass", gramsEquivalent: 250, label: "1 glass", isDefault: true },
  { foodSlug: "tea-with-milk-sugar", unit: "glass", gramsEquivalent: 150, label: "1 cup", isDefault: true },
  { foodSlug: "coffee-with-milk-sugar", unit: "glass", gramsEquivalent: 150, label: "1 cup", isDefault: true },
  { foodSlug: "black-tea-unsweetened", unit: "glass", gramsEquivalent: 150, label: "1 cup", isDefault: true },
  { foodSlug: "buttermilk-spiced", unit: "glass", gramsEquivalent: 250, label: "1 glass", isDefault: true },

  // Curd / yogurt / paneer
  { foodSlug: "curd-plain", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },
  { foodSlug: "curd-low-fat", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },
  { foodSlug: "yogurt-greek", unit: "bowl", gramsEquivalent: 170, label: "1 small tub", isDefault: true },
  { foodSlug: "raita", unit: "katori", gramsEquivalent: 100, label: "1 katori", isDefault: true },
  { foodSlug: "paneer-bhurji", unit: "katori", gramsEquivalent: 100, label: "1 katori", isDefault: true },
  { foodSlug: "paneer-curry", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },

  // Rice / grains
  { foodSlug: "rice-white-cooked", unit: "cup", gramsEquivalent: 150, label: "1 cup", isDefault: true },
  { foodSlug: "rice-brown-cooked", unit: "cup", gramsEquivalent: 150, label: "1 cup", isDefault: true },
  { foodSlug: "biryani-chicken", unit: "cup", gramsEquivalent: 200, label: "1 cup / 1 plate", isDefault: true },
  { foodSlug: "pulao-vegetable", unit: "cup", gramsEquivalent: 180, label: "1 cup", isDefault: true },
  { foodSlug: "curd-rice", unit: "bowl", gramsEquivalent: 180, label: "1 bowl", isDefault: true },
  { foodSlug: "lemon-rice", unit: "cup", gramsEquivalent: 180, label: "1 cup", isDefault: true },

  // Breads
  { foodSlug: "roti-whole-wheat", unit: "roti", gramsEquivalent: 40, label: "1 roti", isDefault: true },
  { foodSlug: "chapati-plain", unit: "chapati", gramsEquivalent: 35, label: "1 chapati", isDefault: true },
  { foodSlug: "paratha-plain", unit: "piece", gramsEquivalent: 70, label: "1 paratha", isDefault: true },
  { foodSlug: "paratha-aloo", unit: "piece", gramsEquivalent: 100, label: "1 aloo paratha", isDefault: true },
  { foodSlug: "naan-plain", unit: "piece", gramsEquivalent: 90, label: "1 naan", isDefault: true },
  { foodSlug: "brown-bread", unit: "slice", gramsEquivalent: 30, label: "1 slice", isDefault: true },
  { foodSlug: "white-bread", unit: "slice", gramsEquivalent: 27, label: "1 slice", isDefault: true },

  // South Indian breakfast
  { foodSlug: "dosa-plain", unit: "piece", gramsEquivalent: 90, label: "1 dosa", isDefault: true },
  { foodSlug: "idli", unit: "piece", gramsEquivalent: 35, label: "1 idli", isDefault: true },
  { foodSlug: "upma", unit: "bowl", gramsEquivalent: 180, label: "1 bowl", isDefault: true },
  { foodSlug: "poha", unit: "bowl", gramsEquivalent: 150, label: "1 bowl", isDefault: true },
  { foodSlug: "besan-chilla", unit: "piece", gramsEquivalent: 80, label: "1 chilla", isDefault: true },
  { foodSlug: "oats-cooked-plain", unit: "bowl", gramsEquivalent: 200, label: "1 bowl", isDefault: true },

  // Dals / legumes
  { foodSlug: "toor-dal-cooked", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },
  { foodSlug: "moong-dal-cooked", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },
  { foodSlug: "chana-dal-cooked", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },
  { foodSlug: "masoor-dal-cooked", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },
  { foodSlug: "urad-dal-cooked", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },
  { foodSlug: "rajma-curry", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },
  { foodSlug: "chole-curry", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },
  { foodSlug: "dal-makhani", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },
  { foodSlug: "sprouts-salad", unit: "katori", gramsEquivalent: 100, label: "1 katori", isDefault: true },
  { foodSlug: "boiled-chickpea-salad", unit: "katori", gramsEquivalent: 120, label: "1 katori", isDefault: true },

  // Sambar / rasam
  { foodSlug: "sambar", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },
  { foodSlug: "rasam", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },

  // Vegetables
  { foodSlug: "aloo-sabzi", unit: "katori", gramsEquivalent: 120, label: "1 katori", isDefault: true },
  { foodSlug: "bhindi-fry", unit: "katori", gramsEquivalent: 100, label: "1 katori", isDefault: true },
  { foodSlug: "baingan-bharta", unit: "katori", gramsEquivalent: 120, label: "1 katori", isDefault: true },
  { foodSlug: "mixed-vegetable-curry", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },
  { foodSlug: "palak-paneer", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },
  { foodSlug: "cabbage-sabzi", unit: "katori", gramsEquivalent: 100, label: "1 katori", isDefault: true },
  { foodSlug: "cauliflower-sabzi", unit: "katori", gramsEquivalent: 100, label: "1 katori", isDefault: true },
  { foodSlug: "methi-sabzi", unit: "katori", gramsEquivalent: 100, label: "1 katori", isDefault: true },
  { foodSlug: "sweet-potato-boiled", unit: "piece", gramsEquivalent: 130, label: "1 medium", isDefault: true },
  { foodSlug: "potato-boiled", unit: "piece", gramsEquivalent: 150, label: "1 medium", isDefault: true },

  // Fruits
  { foodSlug: "banana", unit: "piece", gramsEquivalent: 120, label: "1 medium banana", isDefault: true },
  { foodSlug: "apple", unit: "piece", gramsEquivalent: 180, label: "1 medium apple", isDefault: true },
  { foodSlug: "papaya", unit: "bowl", gramsEquivalent: 150, label: "1 bowl chopped", isDefault: true },
  { foodSlug: "orange", unit: "piece", gramsEquivalent: 130, label: "1 medium orange", isDefault: true },
  { foodSlug: "mango", unit: "piece", gramsEquivalent: 200, label: "1 medium mango", isDefault: true },
  { foodSlug: "watermelon", unit: "bowl", gramsEquivalent: 200, label: "1 bowl chopped", isDefault: true },
  { foodSlug: "grapes", unit: "bowl", gramsEquivalent: 100, label: "1 small bowl", isDefault: true },
  { foodSlug: "pomegranate", unit: "bowl", gramsEquivalent: 100, label: "1 small bowl (arils)", isDefault: true },

  // Nuts (small serving units)
  { foodSlug: "almonds", unit: "piece", gramsEquivalent: 1.2, label: "1 almond" },
  { foodSlug: "almonds", unit: "serving", gramsEquivalent: 28, label: "1 handful (~23 almonds)", isDefault: true },
  { foodSlug: "peanuts", unit: "serving", gramsEquivalent: 30, label: "1 handful", isDefault: true },
  { foodSlug: "cashews", unit: "piece", gramsEquivalent: 2, label: "1 cashew" },
  { foodSlug: "cashews", unit: "serving", gramsEquivalent: 30, label: "1 handful", isDefault: true },
  { foodSlug: "walnuts", unit: "piece", gramsEquivalent: 10, label: "1 walnut (halves)" },
  { foodSlug: "walnuts", unit: "serving", gramsEquivalent: 30, label: "1 handful", isDefault: true },

  // Oils / ghee (spoon-based)
  { foodSlug: "sunflower-oil", unit: "teaspoon", gramsEquivalent: 4.5, label: "1 tsp", isDefault: true },
  { foodSlug: "sunflower-oil", unit: "tablespoon", gramsEquivalent: 13.5, label: "1 tbsp" },
  { foodSlug: "mustard-oil", unit: "teaspoon", gramsEquivalent: 4.5, label: "1 tsp", isDefault: true },
  { foodSlug: "olive-oil", unit: "teaspoon", gramsEquivalent: 4.5, label: "1 tsp", isDefault: true },
  { foodSlug: "ghee", unit: "teaspoon", gramsEquivalent: 4.5, label: "1 tsp", isDefault: true },
  { foodSlug: "ghee", unit: "tablespoon", gramsEquivalent: 13.5, label: "1 tbsp" },

  // Sugar
  { foodSlug: "sugar-white", unit: "teaspoon", gramsEquivalent: 4, label: "1 tsp", isDefault: true },
  { foodSlug: "jaggery", unit: "teaspoon", gramsEquivalent: 5, label: "1 tsp", isDefault: true },

  // Snacks
  { foodSlug: "namkeen-mixture", unit: "serving", gramsEquivalent: 30, label: "1 small handful", isDefault: true },
  { foodSlug: "biscuits-marie", unit: "piece", gramsEquivalent: 6, label: "1 biscuit", isDefault: true },
  { foodSlug: "biscuits-digestive", unit: "piece", gramsEquivalent: 14, label: "1 biscuit", isDefault: true },
  { foodSlug: "samosa", unit: "piece", gramsEquivalent: 70, label: "1 samosa", isDefault: true },

  // Restaurant style
  { foodSlug: "butter-chicken", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },
  { foodSlug: "chicken-tikka-masala", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },
  { foodSlug: "paneer-tikka-masala", unit: "katori", gramsEquivalent: 150, label: "1 katori", isDefault: true },
  { foodSlug: "egg-roll-kathi", unit: "piece", gramsEquivalent: 180, label: "1 roll", isDefault: true },

  // Salads / condiments / soup
  { foodSlug: "chicken-soup", unit: "bowl", gramsEquivalent: 200, label: "1 bowl", isDefault: true },
  { foodSlug: "coconut-chutney", unit: "tablespoon", gramsEquivalent: 15, label: "1 tbsp", isDefault: true },
  { foodSlug: "peanut-chutney", unit: "tablespoon", gramsEquivalent: 15, label: "1 tbsp", isDefault: true },
];

// ─────────────────────────── FOOD ALIASES ───────────────────────────

export const foodAliasSeed: { foodSlug: string; alias: string }[] = [
  // Roti / chapati / phulka family
  { foodSlug: "roti-whole-wheat", alias: "roti" },
  { foodSlug: "roti-whole-wheat", alias: "chapati" },
  { foodSlug: "roti-whole-wheat", alias: "phulka" },
  { foodSlug: "roti-whole-wheat", alias: "fulka" },
  { foodSlug: "chapati-plain", alias: "chapathi" },
  { foodSlug: "chapati-plain", alias: "roti" },

  // Curd / yogurt / dahi family
  { foodSlug: "curd-plain", alias: "yogurt" },
  { foodSlug: "curd-plain", alias: "dahi" },
  { foodSlug: "curd-plain", alias: "yoghurt" },
  { foodSlug: "curd-plain", alias: "curds" },

  // Brinjal / eggplant / baingan family
  { foodSlug: "baingan-bharta", alias: "brinjal" },
  { foodSlug: "baingan-bharta", alias: "eggplant" },
  { foodSlug: "baingan-bharta", alias: "baingan" },
  { foodSlug: "baingan-bharta", alias: "aubergine" },

  // Bhindi / ladyfinger / okra family
  { foodSlug: "bhindi-fry", alias: "bhindi" },
  { foodSlug: "bhindi-fry", alias: "ladyfinger" },
  { foodSlug: "bhindi-fry", alias: "lady finger" },
  { foodSlug: "bhindi-fry", alias: "okra" },

  // Peanut / groundnut family
  { foodSlug: "peanuts", alias: "groundnut" },
  { foodSlug: "peanuts", alias: "groundnuts" },
  { foodSlug: "peanuts", alias: "peanut" },
  { foodSlug: "peanuts", alias: "moongphali" },

  // Eggs
  { foodSlug: "egg-boiled", alias: "anda" },
  { foodSlug: "egg-boiled", alias: "boiled anda" },
  { foodSlug: "egg-curry", alias: "anda curry" },
  { foodSlug: "egg-curry", alias: "anda masala" },
  { foodSlug: "egg-bhurji", alias: "anda bhurji" },
  { foodSlug: "egg-bhurji", alias: "egg scramble" },
  { foodSlug: "egg-bhurji", alias: "scrambled egg" },
  { foodSlug: "omelette-plain", alias: "omelet" },
  { foodSlug: "omelette-plain", alias: "anda omelette" },

  // Chicken / murgh family
  { foodSlug: "chicken-curry-home-style", alias: "murgh curry" },
  { foodSlug: "chicken-curry-home-style", alias: "chicken gravy" },
  { foodSlug: "chicken-curry-home-style", alias: "kozhi curry" },
  { foodSlug: "chicken-tandoori", alias: "tandoori murgh" },
  { foodSlug: "chicken-tikka-masala", alias: "ctm" },
  { foodSlug: "chicken-breast-raw", alias: "murgh breast" },
  { foodSlug: "chicken-breast-grilled", alias: "grilled murgh" },
  { foodSlug: "chicken-65", alias: "chicken sixty five" },
  { foodSlug: "chicken-drumstick-roasted", alias: "murgh drumstick" },

  // Mutton / gosht family
  { foodSlug: "mutton-curry", alias: "gosht" },
  { foodSlug: "mutton-curry", alias: "gosht curry" },
  { foodSlug: "mutton-curry", alias: "goat curry" },
  { foodSlug: "mutton-curry", alias: "mutton gravy" },
  { foodSlug: "mutton-keema", alias: "keema" },
  { foodSlug: "mutton-keema", alias: "gosht keema" },
  { foodSlug: "mutton-keema", alias: "minced mutton" },
  { foodSlug: "mutton-raw", alias: "goat meat" },

  // Fish family
  { foodSlug: "fish-curry-rohu", alias: "meen curry" },
  { foodSlug: "fish-curry-rohu", alias: "rohu curry" },
  { foodSlug: "fish-fry-pomfret", alias: "pomfret fry" },
  { foodSlug: "fish-fry-pomfret", alias: "meen fry" },
  { foodSlug: "fish-raw-rohu", alias: "rohu" },
  { foodSlug: "fish-raw-rohu", alias: "rui fish" },

  // Prawns
  { foodSlug: "prawns-curry", alias: "shrimp curry" },
  { foodSlug: "prawns-fried", alias: "shrimp fry" },
  { foodSlug: "prawns-raw", alias: "shrimp" },

  // Paneer
  { foodSlug: "paneer-raw", alias: "cottage cheese" },
  { foodSlug: "paneer-bhurji", alias: "paneer scramble" },
  { foodSlug: "paneer-curry", alias: "paneer masala" },
  { foodSlug: "paneer-curry", alias: "shahi paneer" },

  // Rice / biryani family
  { foodSlug: "rice-white-cooked", alias: "chawal" },
  { foodSlug: "rice-white-cooked", alias: "steamed rice" },
  { foodSlug: "biryani-chicken", alias: "biriyani" },
  { foodSlug: "biryani-chicken", alias: "byriani" },
  { foodSlug: "biryani-chicken", alias: "briyani" },
  { foodSlug: "biryani-chicken", alias: "chicken biriyani" },
  { foodSlug: "pulao-vegetable", alias: "veg pulav" },
  { foodSlug: "pulao-vegetable", alias: "pulav" },
  { foodSlug: "curd-rice", alias: "thayir sadam" },
  { foodSlug: "lemon-rice", alias: "chitranna" },

  // Dals
  { foodSlug: "toor-dal-cooked", alias: "arhar dal" },
  { foodSlug: "toor-dal-cooked", alias: "tuvar dal" },
  { foodSlug: "moong-dal-cooked", alias: "mung dal" },
  { foodSlug: "chana-dal-cooked", alias: "bengal gram dal" },
  { foodSlug: "masoor-dal-cooked", alias: "red lentil dal" },
  { foodSlug: "urad-dal-cooked", alias: "black gram dal" },
  { foodSlug: "rajma-curry", alias: "kidney bean curry" },
  { foodSlug: "chole-curry", alias: "chana masala" },
  { foodSlug: "chole-curry", alias: "chickpea curry" },

  // South Indian breakfast
  { foodSlug: "dosa-plain", alias: "dose" },
  { foodSlug: "idli", alias: "idly" },
  { foodSlug: "upma", alias: "uppuma" },
  { foodSlug: "upma", alias: "uppittu" },
  { foodSlug: "poha", alias: "pohe" },
  { foodSlug: "poha", alias: "chivda" },
  { foodSlug: "besan-chilla", alias: "chilla" },
  { foodSlug: "besan-chilla", alias: "besan cheela" },

  // Sambar / rasam
  { foodSlug: "sambar", alias: "sambhar" },
  { foodSlug: "rasam", alias: "saaru" },
  { foodSlug: "rasam", alias: "charu" },

  // Fruits
  { foodSlug: "banana", alias: "kela" },
  { foodSlug: "papaya", alias: "papita" },
  { foodSlug: "orange", alias: "santra" },
  { foodSlug: "mango", alias: "aam" },
  { foodSlug: "grapes", alias: "angoor" },
  { foodSlug: "pomegranate", alias: "anar" },

  // Vegetables
  { foodSlug: "aloo-sabzi", alias: "potato sabzi" },
  { foodSlug: "potato-boiled", alias: "aloo" },
  { foodSlug: "cauliflower-sabzi", alias: "gobi" },
  { foodSlug: "cauliflower-sabzi", alias: "gobi sabzi" },
  { foodSlug: "spinach-raw", alias: "palak" },
  { foodSlug: "methi-sabzi", alias: "methi" },
  { foodSlug: "methi-sabzi", alias: "fenugreek leaves" },
  { foodSlug: "onion-raw", alias: "pyaz" },
  { foodSlug: "onion-raw", alias: "kanda" },
  { foodSlug: "tomato", alias: "tamatar" },
  { foodSlug: "cabbage-sabzi", alias: "patta gobi sabzi" },
  { foodSlug: "sweet-potato-boiled", alias: "shakarkandi" },

  // Milk / dairy / beverages
  { foodSlug: "milk-full-fat", alias: "doodh" },
  { foodSlug: "buttermilk-spiced", alias: "chaas" },
  { foodSlug: "buttermilk-spiced", alias: "chhaas" },
  { foodSlug: "buttermilk-spiced", alias: "majjige" },
  { foodSlug: "tea-with-milk-sugar", alias: "chai" },
  { foodSlug: "coffee-with-milk-sugar", alias: "filter coffee" },
  { foodSlug: "coffee-with-milk-sugar", alias: "kaapi" },

  // Oils / ghee / sugar
  { foodSlug: "ghee", alias: "clarified butter" },
  { foodSlug: "sugar-white", alias: "cheeni" },
  { foodSlug: "sugar-white", alias: "chini" },
  { foodSlug: "jaggery", alias: "gur" },
  { foodSlug: "jaggery", alias: "gud" },

  // Whey / supplements
  { foodSlug: "whey-protein-generic", alias: "protein powder" },
  { foodSlug: "whey-protein-generic", alias: "whey" },

  // Restaurant style
  { foodSlug: "butter-chicken", alias: "murgh makhani" },
  { foodSlug: "butter-chicken", alias: "makhani chicken" },
  { foodSlug: "dal-makhani", alias: "dal makhni" },
  { foodSlug: "samosa", alias: "samosas" },
  { foodSlug: "namkeen-mixture", alias: "chivda mix" },
  { foodSlug: "namkeen-mixture", alias: "mixture" },
];
