/**
 * Generates supabase/seed-reference-data.sql — the global reference data (equipment,
 * exercise directory, food database) that has no user_id and is safe to paste into the
 * Supabase SQL editor once, before anyone signs in. User-owned data (profile, programme,
 * workout history, food logs) is seeded client-side after sign-in instead — see
 * lib/data/seedSupabaseUser.ts — because it needs a real auth.users id that only exists
 * once the user has an account.
 *
 * Run with: npx tsx db/seed/generateSql.ts
 */
import { writeFileSync } from "node:fs";
import { randomUUID } from "node:crypto";
import { equipmentSeed } from "./equipment";
import { exerciseSeed, exerciseAliasSeed, exerciseSubstitutionSeed } from "./exercises";
import { foodItemSeed, foodServingSeed, foodAliasSeed } from "./foods";

function sqlString(value: string | null | undefined): string {
  if (value === null || value === undefined) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}
function sqlNumber(value: number | null | undefined): string {
  if (value === null || value === undefined) return "null";
  return String(value);
}
function sqlBool(value: boolean): string {
  return value ? "true" : "false";
}
function sqlArray(values: string[]): string {
  if (values.length === 0) return "'{}'";
  return `ARRAY[${values.map(sqlString).join(", ")}]::text[]`;
}

const lines: string[] = [];
lines.push("-- Nithish Fit: global reference data (equipment, exercises, foods).");
lines.push("-- Generated by db/seed/generateSql.ts — safe to run once, before any user signs up.");
lines.push("-- Paste into the Supabase SQL editor AFTER running supabase/migrations/*.sql.");
lines.push("");
lines.push("begin;");
lines.push("");

// ---- Equipment ----
lines.push("-- Equipment catalogue");
for (const eq of equipmentSeed) {
  lines.push(
    `insert into equipment (type, name, notes) values (${sqlString(eq.type)}, ${sqlString(eq.name)}, ${sqlString(eq.notes ?? null)}) on conflict (type) do nothing;`
  );
}
lines.push("");

// ---- Exercises ----
lines.push("-- Exercise directory");
for (const e of exerciseSeed) {
  lines.push(
    `insert into exercises (slug, name, primary_muscles, secondary_muscles, movement_pattern, equipment, is_compound, is_unilateral, load_basis, setup_instructions, execution_instructions, breathing_guidance, common_mistakes, wrist_load_category, recommended_grip, per_hand_or_total_note, safety_note, contraindications, per_hand_weight_limit_kg, suggested_rep_range_low, suggested_rep_range_high, progression_method, substitute_exercise_slugs, video_url, is_selectable_by_default) values (` +
      [
        sqlString(e.slug),
        sqlString(e.name),
        sqlArray(e.primaryMuscles),
        sqlArray(e.secondaryMuscles),
        sqlString(e.movementPattern),
        sqlArray(e.equipment),
        sqlBool(e.isCompound),
        sqlBool(e.isUnilateral),
        sqlString(e.loadBasis),
        sqlString(e.setupInstructions),
        sqlString(e.executionInstructions),
        sqlString(e.breathingGuidance),
        sqlArray(e.commonMistakes),
        sqlString(e.wristLoadCategory),
        sqlString(e.recommendedGrip),
        sqlString(e.perHandOrTotalNote),
        sqlString(e.safetyNote),
        sqlArray(e.contraindications),
        sqlNumber(e.perHandWeightLimitKg),
        sqlNumber(e.suggestedRepRangeLow),
        sqlNumber(e.suggestedRepRangeHigh),
        sqlString(e.progressionMethod),
        sqlArray(e.substituteExerciseSlugs),
        sqlString(e.videoUrl),
        sqlBool(e.isSelectableByDefault),
      ].join(", ") +
      `) on conflict (slug) do nothing;`
  );
}
lines.push("");

lines.push("-- Exercise aliases");
for (const a of exerciseAliasSeed) {
  lines.push(`insert into exercise_aliases (exercise_slug, alias) values (${sqlString(a.exerciseSlug)}, ${sqlString(a.alias)});`);
}
lines.push("");

lines.push("-- Exercise substitutions");
for (const s of exerciseSubstitutionSeed) {
  lines.push(
    `insert into exercise_substitutions (exercise_slug, substitute_slug, reason) values (${sqlString(s.exerciseSlug)}, ${sqlString(s.substituteSlug)}, ${sqlString(s.reason)});`
  );
}
lines.push("");

// ---- Food items (need explicit UUIDs since food_servings/food_aliases reference them by id) ----
const foodIdBySlug = new Map<string, string>();
for (const f of foodItemSeed) foodIdBySlug.set(f.slug, randomUUID());

lines.push("-- Food database");
for (const f of foodItemSeed) {
  const id = foodIdBySlug.get(f.slug)!;
  lines.push(
    `insert into food_items (id, slug, name, category, cuisine_tag, raw_cooked_state, preparation_method, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g, fibre_per_100g, source, measurement_basis, reliability, last_updated, is_custom, owner_user_id) values (` +
      [
        sqlString(id),
        sqlString(f.slug),
        sqlString(f.name),
        sqlString(f.category),
        sqlString(f.cuisineTag ?? null),
        sqlString(f.rawCookedState),
        sqlString(f.preparationMethod ?? null),
        sqlNumber(f.caloriesPer100g),
        sqlNumber(f.proteinPer100g),
        sqlNumber(f.carbsPer100g),
        sqlNumber(f.fatPer100g),
        sqlNumber(f.fibrePer100g),
        sqlString(f.source),
        sqlString(f.measurementBasis),
        sqlString(f.reliability),
        sqlString(f.lastUpdated),
        sqlBool(false),
        "null",
      ].join(", ") +
      `) on conflict (slug) do nothing;`
  );
}
lines.push("");

lines.push("-- Food servings");
for (const s of foodServingSeed) {
  const foodId = foodIdBySlug.get(s.foodSlug);
  if (!foodId) continue;
  lines.push(
    `insert into food_servings (food_item_id, unit, grams_equivalent, label, is_default) values (${sqlString(foodId)}, ${sqlString(s.unit)}, ${sqlNumber(s.gramsEquivalent)}, ${sqlString(s.label)}, ${sqlBool(s.isDefault ?? false)});`
  );
}
lines.push("");

lines.push("-- Food aliases");
for (const a of foodAliasSeed) {
  const foodId = foodIdBySlug.get(a.foodSlug);
  if (!foodId) continue;
  lines.push(`insert into food_aliases (food_item_id, alias, is_user_correction, owner_user_id) values (${sqlString(foodId)}, ${sqlString(a.alias)}, false, null);`);
}
lines.push("");
lines.push("commit;");

const sql = lines.join("\n") + "\n";
writeFileSync(new URL("../../supabase/seed-reference-data.sql", import.meta.url), sql, "utf8");
console.log(`Wrote supabase/seed-reference-data.sql (${lines.length} lines, ${exerciseSeed.length} exercises, ${foodItemSeed.length} foods)`);
