export const FOOD_UNITS = [
  "gram",
  "kilogram",
  "millilitre",
  "litre",
  "teaspoon",
  "tablespoon",
  "cup",
  "glass",
  "bowl",
  "katori",
  "piece",
  "slice",
  "roti",
  "chapati",
  "scoop",
  "serving",
] as const;
export type FoodUnit = (typeof FOOD_UNITS)[number];

/** Maps common written/spoken forms (including Indian regional variants) to canonical units. */
export const UNIT_ALIASES: Record<string, FoodUnit> = {
  g: "gram",
  gm: "gram",
  gms: "gram",
  gram: "gram",
  grams: "gram",
  kg: "kilogram",
  kgs: "kilogram",
  kilo: "kilogram",
  kilos: "kilogram",
  kilogram: "kilogram",
  kilograms: "kilogram",
  ml: "millilitre",
  mls: "millilitre",
  millilitre: "millilitre",
  millilitres: "millilitre",
  milliliter: "millilitre",
  l: "litre",
  ltr: "litre",
  litre: "litre",
  litres: "litre",
  liter: "litre",
  tsp: "teaspoon",
  teaspoon: "teaspoon",
  teaspoons: "teaspoon",
  tbsp: "tablespoon",
  tablespoon: "tablespoon",
  tablespoons: "tablespoon",
  cup: "cup",
  cups: "cup",
  glass: "glass",
  glasses: "glass",
  bowl: "bowl",
  bowls: "bowl",
  katori: "katori",
  katoris: "katori",
  piece: "piece",
  pieces: "piece",
  pc: "piece",
  pcs: "piece",
  slice: "slice",
  slices: "slice",
  roti: "roti",
  rotis: "roti",
  phulka: "roti",
  phulkas: "roti",
  chapati: "chapati",
  chapatis: "chapati",
  chappati: "chapati",
  scoop: "scoop",
  scoops: "scoop",
  serving: "serving",
  servings: "serving",
  katori_: "katori",
};

/** Generic gram-equivalent fallback per unit, used only when no food-specific FoodServing exists. */
export const DEFAULT_UNIT_GRAMS: Record<FoodUnit, number> = {
  gram: 1,
  kilogram: 1000,
  millilitre: 1,
  litre: 1000,
  teaspoon: 5,
  tablespoon: 15,
  cup: 240,
  glass: 250,
  bowl: 200,
  katori: 150,
  piece: 50,
  slice: 25,
  roti: 40,
  chapati: 40,
  scoop: 30,
  serving: 100,
};

export function normalizeUnit(raw: string): FoodUnit | null {
  const key = raw.trim().toLowerCase().replace(/\.$/, "");
  return UNIT_ALIASES[key] ?? null;
}
